import pandas as pd

# Use your own file path and pass either a csv file or .txt file generated by spark.c
df = pd.read_csv("temp-main/kit/lab2_kit/spark/out.txt", sep="\t")

# Gets sizes that are going to be testes
sizes = df["size"].unique()

# Iterates over each size and gathers, elapsed time, #accesses and #MAT
for size in sizes:
    values = df[df["size"] == size]
    mean_elapsed = values["elapsed(s)"].mean()
    access = 0
    for index, row in values.iterrows():
        access += int(row["size"]) / int(row["stride"])
    print("Size: {:.2f} \n| t2-t1 (mean): {:.3f} \n| #access: {:.0f} \n| mean time (micro seconds): {:}"
          .format(size, mean_elapsed, access, (mean_elapsed / access) * 10 ** 6))
